### ISSUE TITLE
When searching  old results appear

### ISSUE THREAD

**Issue by rdinicut** [centrifuge/documentation#95]
Search seems to be cached and when searching old results appear.
Ex:when  typing webhooks the search returns https://developer.centrifuge.io/docs/getting-started/install-cent-node#additional-custom-configuration which does not exist anymore

We need to login in agnolia and reset the cache

**Comment by lucasvo** [comment]
https://www.netlify.com/blog/2021/01/20/how-algolia-created-its-netlify-build-plugin/ < this seems to solve it.

**Comment by lucasvo** [comment]
We should move away from netlify deploys and use github actions as we do in the apps repo and then migrate over to using the github action instead of using a netlify plugin.

This ticket should address:
1) Updating to a github action triggered deploy (see this example: https://github.com/centrifuge/apps/blob/main/.github/workflows/tinlake-ui-deploy-to-prod.yml)
2) Using this action after the netlify deploy to update the index: github.com/marketplace/actions/algolia-docsearch-indexer
